### ISSUE TITLE
Invalid Zip

### ISSUE THREAD

**Issue by SachinKarinki** [Yusuf6411/PowerBoost#1]
Hello, The module is showing as it's not a Magisk module because, the zip is not properly done, inside the zip there is a powerboost folder, but it shouldn't be like that, the zip must be made with contents inside the folder only. I have already resolved issue on my own, I am just reporting the issue, so it can be resolved in next update. 
![IMG_20241214_062159](https://github.com/user-attachments/assets/d15e3e8d-eb3f-4d08-a801-1f73aa5377d4)

**Comment by Yusuf6411** [comment]
Hi
Sorry for the error
I have fixed this is the new release
Please let me know if you want any additional features
